apiVersion: v2
description: A Helm chart for the app-operator
home: https://github.com/giantswarm/app-operator
name: app-operator
appVersion: 7.5.2
version: 7.5.2
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.team: honeybadger
